# Generated by Django 6.0.2 on 2026-02-19 01:54

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, help_text='Maps to the e-commerce store product ID (received from webhook).', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich description of the book shown in the Library/Store.')),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image (3D render preferred).', null=True, upload_to='books/covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('archived', 'Archived')], default='active', max_length=15)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the Library. Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Icon/image for this specialty.', null=True, upload_to='books/specialty_icons/')),
                ('description', models.TextField(blank=True, help_text='Brief description of this specialty.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='books.book')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['display_order', 'name'],
                'unique_together': {('book', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich HTML content — supports headers, images, tables, clinical photos.')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='List of key point strings. Example: ["Point 1", "Point 2"]')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_board_basics', models.BooleanField(default=False, help_text='If checked, this topic also appears in the Board Basics section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='books.specialty')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['display_order', 'title'],
                'unique_together': {('specialty', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserBookAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, help_text='Order ID from the webhook payload.', max_length=100)),
                ('source', models.CharField(choices=[('webhook', 'Webhook (Auto)'), ('manual_admin', 'Manual (Admin)')], default='webhook', max_length=15)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Access',
                'verbose_name_plural': 'User Book Access',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
