# Generated by Django 6.0.2 on 2026-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='estimated_pages',
            field=models.PositiveIntegerField(default=0, help_text='Total page count for progress display (e.g., "450 / 870 pages").'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='core_display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance in the CORE badge list (1-11).'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_core_specialty',
            field=models.BooleanField(default=False, help_text='If True, this specialty appears in the CORE certification module with badge tracking.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_tasks',
            field=models.PositiveIntegerField(default=0, help_text='Number of tasks associated with this topic (for Learning Plan progress display).'),
        ),
    ]
