# Generated by Django 6.0.2 on 2026-03-10 19:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_estimated_pages_specialty_core_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The full book PDF file. Specialties and topics are mapped to page ranges within this PDF.', null=True, upload_to='books/pdfs/'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, help_text='Total number of pages in the PDF (auto-set or manually entered).'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='end_page',
            field=models.PositiveIntegerField(default=0, help_text='Ending page number in the book PDF for this specialty (inclusive).'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='start_page',
            field=models.PositiveIntegerField(default=0, help_text='Starting page number in the book PDF for this specialty (1-indexed).'),
        ),
        migrations.AddField(
            model_name='topic',
            name='end_page',
            field=models.PositiveIntegerField(default=0, help_text='Ending page number in the book PDF for this topic (inclusive).'),
        ),
        migrations.AddField(
            model_name='topic',
            name='start_page',
            field=models.PositiveIntegerField(default=0, help_text='Starting page number in the book PDF for this topic (1-indexed).'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='[DEPRECATED — use PDF page ranges instead] Rich HTML content.'),
        ),
    ]
