# Generated by Django 6.0.2 on 2026-03-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pdf_file_book_total_pages_specialty_end_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
