# Generated by Django 6.0.2 on 2026-03-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='estimated_tasks',
        ),
    ]
