# Generated by Django 6.0.2 on 2026-02-19 01:54

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', django_ckeditor_5.fields.CKEditor5Field(help_text='The question/prompt side of the flashcard.')),
                ('back_text', django_ckeditor_5.fields.CKEditor5Field(help_text='The answer/explanation side of the flashcard.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(help_text='The specialty this flashcard belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='books.specialty')),
                ('topic', models.ForeignKey(blank=True, help_text='Optional: specific topic this flashcard relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='books.topic')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['specialty__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCustomFlashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front_text', models.TextField(help_text='The question/prompt side.')),
                ('back_text', models.TextField(help_text='The answer/explanation side.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, help_text='Topic this flashcard was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_flashcards', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Flashcard',
                'verbose_name_plural': 'User Custom Flashcards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.IntegerField(choices=[(0, 'Not Reviewed'), (1, 'Not Confident'), (2, 'Somewhat Confident'), (3, 'Confident'), (4, 'Very Confident')], default=0)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='flashcards.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Progress',
                'verbose_name_plural': 'Flashcard Progress',
                'ordering': ['next_review_at'],
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
