# Generated by Django 6.0.2 on 2026-03-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_estimated_pages_specialty_core_display_order_and_more'),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['book__title', 'display_order', 'created_at'], 'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='book',
            field=models.ForeignKey(blank=True, help_text='The book this flashcard belongs to (defines the deck).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='books.book'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the deck. Determines position in "2/215 Flashcards" counter.'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='related_topic',
            field=models.ForeignKey(blank=True, help_text='Topic linked via "Related Text →" on the answer side.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_flashcards', to='books.topic'),
        ),
        migrations.AlterField(
            model_name='userflashcardprogress',
            name='confidence',
            field=models.IntegerField(choices=[(0, 'Not Reviewed'), (1, 'Viewed'), (2, 'Somewhat Confident'), (3, 'Confident'), (4, 'Very Confident')], default=0),
        ),
    ]
