# Generated by Django 6.0.2 on 2026-03-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_options_flashcard_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomFlashcard',
        ),
    ]
