# Generated by Django 6.0.2 on 2026-02-19 01:54

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(help_text='The question stem. Can include formatted text, images, and tables.')),
                ('question_image', models.ImageField(blank=True, help_text='Optional clinical image/figure for the question.', null=True, upload_to='questions/images/')),
                ('option_a', models.TextField(help_text='Option A text.')),
                ('option_b', models.TextField(help_text='Option B text.')),
                ('option_c', models.TextField(help_text='Option C text.')),
                ('option_d', models.TextField(help_text='Option D text.')),
                ('option_e', models.TextField(blank=True, help_text='Option E text (optional for 4-option questions).')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Which option is the correct answer.', max_length=1)),
                ('explanation', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed explanation shown after answering.')),
                ('educational_objective', models.TextField(blank=True, help_text='The educational objective tested by this question.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(help_text='The specialty this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='books.specialty')),
                ('topic', models.ForeignKey(blank=True, help_text='Optional: specific topic this question relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='books.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['specialty__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam Mode')], default='practice', max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('specialties', models.ManyToManyField(blank=True, help_text='Specialties included in this quiz.', to='books.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_saved', models.BooleanField(default=False, help_text='User bookmarked/saved this question.')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': 'Question Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
