# Generated by Django 6.0.2 on 2026-03-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='care_type',
            field=models.CharField(blank=True, choices=[('ambulatory', 'Ambulatory'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('icu', 'ICU / Critical Care')], help_text='Care setting tag (e.g., "Ambulatory", "Inpatient").', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='key_point',
            field=models.TextField(blank=True, help_text='Standalone key takeaway shown in a separate "Key Point" card.'),
        ),
        migrations.AddField(
            model_name='question',
            name='lab_values',
            field=models.JSONField(blank=True, default=list, help_text='Lab values with abnormal flags. Example: [{"name": "Hemoglobin", "value": "8.2", "unit": "g/dL", "flag": "L", "ref_range": "12-16"}]'),
        ),
        migrations.AddField(
            model_name='question',
            name='patient_demographic',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('elderly', 'Age ≥65 y'), ('young_adult', 'Age 18-40 y'), ('pregnant', 'Pregnant'), ('pediatric', 'Pediatric')], help_text='Patient demographic tag (e.g., "Age ≥65 y").', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='List of reference objects. Example: [{"text": "Author et al.", "pmid": "12345678"}]'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='show_explanations',
            field=models.BooleanField(default=True, help_text='If False, answer & critique are hidden (exam simulation mode).'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='time_limit_per_question',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds per question (null = untimed). Figma options: 60s, 90s.', null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='title',
            field=models.CharField(blank=True, help_text='User-given name for custom quizzes (e.g., "Cardio Review").', max_length=255),
        ),
        migrations.AddField(
            model_name='userquestionattempt',
            name='quiz_session',
            field=models.ForeignKey(blank=True, help_text='The quiz session this attempt belongs to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='questions.quizsession'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam Mode'), ('lka', 'LKA Practice'), ('retry', 'Retry Incorrect')], default='practice', max_length=10),
        ),
    ]
