# Generated by Django 6.0.2 on 2026-03-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pdf_file_book_total_pages_specialty_end_page_and_more'),
        ('questions', '0002_question_care_type_question_key_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='book',
            field=models.ForeignKey(blank=True, help_text='The book this question belongs to (for Question Bank grouping).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='books.book'),
        ),
        migrations.AddField(
            model_name='question',
            name='related_topic',
            field=models.ForeignKey(blank=True, help_text='Topic linked via "Related Syllabus Content →" in the critique section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_questions', to='books.topic'),
        ),
    ]
