# Generated by Django 6.0.2 on 2026-03-15 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='E.g., "support@medigest.com" or "1-800-MEDIGEST"', max_length=200)),
                ('subtitle', models.CharField(help_text='E.g., "Email Support", "Phone Support"', max_length=200)),
                ('icon_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('link', 'Link'), ('chat', 'Chat')], default='email', max_length=20)),
                ('action_text', models.CharField(help_text='E.g., "Get help from our support team →"', max_length=200)),
                ('action_url', models.CharField(help_text='E.g., "mailto:support@medigest.com" or "tel:18006334437"', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Method',
                'verbose_name_plural': 'Contact Methods',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g., "Reading & Textbooks", "Practice Questions"', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(help_text='The answer to the FAQ.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='support.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category__display_order', 'display_order'],
            },
        ),
    ]
