# Generated by Django 6.0.2 on 2026-02-19 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, db_index=True, help_text='Order ID extracted from the webhook payload.', max_length=100)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email from the payload.', max_length=254)),
                ('payload_json', models.JSONField(default=dict, help_text='The complete raw JSON payload received.')),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether the HMAC signature was valid.')),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('invalid_sig', 'Invalid Signature')], default='received', max_length=15)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the webhook sender.', null=True)),
                ('user_created', models.BooleanField(default=False, help_text='Whether a new user was created as a result.')),
                ('books_granted', models.PositiveIntegerField(default=0, help_text='Number of books access was granted for.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
