# Generated by Django 6.0.2 on 2026-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_study_streak',
            field=models.PositiveIntegerField(default=0, help_text='Current consecutive days of study activity.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(blank=True, help_text='Date of last study activity. Used to calculate streak continuity.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_study_streak',
            field=models.PositiveIntegerField(default=0, help_text='All-time longest study streak (for achievements/display).'),
        ),
    ]
