# Generated by Django 6.0.2 on 2026-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_study_streak_user_last_study_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('doctor', 'Doctor')], default='student', max_length=10),
        ),
    ]
