# Generated by Django 6.0.2 on 2026-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_flashcard_goal',
            field=models.PositiveIntegerField(default=60, help_text='Daily flashcard review goal count (default: 60).'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_questions_goal',
            field=models.PositiveIntegerField(default=20, help_text='Daily practice questions goal count (default: 20).'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_reading_goal_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Daily reading time goal in minutes (default: 60).'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Enable/disable push notifications (Settings > Profile tab).'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_reminders',
            field=models.BooleanField(default=True, help_text='Enable/disable study reminder notifications (Settings > Profile tab).'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_reports',
            field=models.BooleanField(default=True, help_text='Enable/disable weekly progress report emails (Settings > Profile tab).'),
        ),
    ]
