# Generated by Django 6.0.2 on 2026-03-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_daily_flashcard_goal_user_daily_questions_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_reading_goal_minutes',
        ),
        migrations.AddField(
            model_name='user',
            name='daily_topics_goal',
            field=models.PositiveIntegerField(default=5, help_text='Daily reading topics goal (default: 5).'),
        ),
    ]
