# Generated by Django 6.0.2 on 2026-02-19 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('core', 'CORE Completion'), ('cme', 'CME Credits'), ('exam', 'Exam Completion')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CMEActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('syllabus', 'Syllabus Reading'), ('quiz', 'Quiz Completion'), ('board_basics', 'Board Basics')], max_length=20)),
                ('credits', models.DecimalField(decimal_places=2, help_text='Number of CME credits earned for completing this activity.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cme_activities', to='books.specialty')),
            ],
            options={
                'verbose_name': 'CME Activity',
                'verbose_name_plural': 'CME Activities',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserCMECredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_earned', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='earned', max_length=15)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to='certificates.cmeactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cme_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User CME Credit',
                'verbose_name_plural': 'User CME Credits',
                'ordering': ['-earned_at'],
            },
        ),
    ]
