# Generated by Django 6.0.2 on 2026-03-01 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_estimated_pages_specialty_core_display_order_and_more'),
        ('certificates', '0001_initial'),
        ('questions', '0002_question_care_type_question_key_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='credit_year',
            field=models.PositiveIntegerField(blank=True, help_text='Calendar year for CME certificates.', null=True),
        ),
        migrations.AddField(
            model_name='usercmecredit',
            name='credit_year',
            field=models.PositiveIntegerField(default=2026, help_text='Calendar year this credit belongs to (e.g., 2026). Credits cap at 300/year.'),
        ),
        migrations.AddField(
            model_name='usercmecredit',
            name='question',
            field=models.ForeignKey(blank=True, help_text='The question answered correctly that earned this credit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cme_credits', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='cmeactivity',
            name='activity_type',
            field=models.CharField(choices=[('syllabus', 'Syllabus Reading'), ('quiz', 'Quiz Completion'), ('board_basics', 'Board Basics'), ('question', 'Individual Question')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usercmecredit',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to='certificates.cmeactivity'),
        ),
        migrations.CreateModel(
            name='CMESubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accreditation_body', models.CharField(choices=[('ama', 'AMA PRA Category 1 Credits™'), ('abim_moc', 'ABIM Maintenance of Certification'), ('canada_rc', 'Royal College of Physicians & Surgeons of Canada'), ('qatar_qchp', 'Qatar Council for Healthcare Practitioners'), ('australia_racp', 'Royal Australasian College of Physicians')], default='ama', max_length=20)),
                ('credits_claimed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_year', models.PositiveIntegerField(help_text='Calendar year for this submission.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('credits', models.ManyToManyField(blank=True, help_text='The individual earned credits included in this submission.', related_name='submissions', to='certificates.usercmecredit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cme_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CME Submission',
                'verbose_name_plural': 'CME Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCOREProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('questions_answered', models.PositiveIntegerField(default=0, help_text='Total questions answered in this specialty.')),
                ('questions_correct', models.PositiveIntegerField(default=0, help_text='Total questions answered correctly.')),
                ('last_30_correct', models.PositiveIntegerField(default=0, help_text='Correct answers in the last 30 questions (for ≥50% threshold).')),
                ('last_30_total', models.PositiveIntegerField(default=0, help_text='Total answers in the last 30 questions window.')),
                ('core_quiz_unlocked', models.BooleanField(default=False, help_text='True when user scores ≥50% on last 30 questions.')),
                ('badge_earned_at', models.DateTimeField(blank=True, help_text='Timestamp when the CORE badge was completed.', null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time the user practiced in this specialty.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(help_text='The CORE specialty this badge tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='core_progress', to='books.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CORE Progress',
                'verbose_name_plural': 'CORE Progress',
                'ordering': ['specialty__name'],
                'unique_together': {('user', 'specialty')},
            },
        ),
    ]
