# Generated by Django 6.0.2 on 2026-02-19 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('reading', 'Reading'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard')], max_length=15)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the related topic/quiz/flashcard.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highlighted_text', models.TextField(help_text='The selected text.')),
                ('start_offset', models.PositiveIntegerField(help_text='Character offset of highlight start.')),
                ('end_offset', models.PositiveIntegerField(help_text='Character offset of highlight end.')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'ordering': ['topic', 'start_offset'],
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The note text.')),
                ('position_offset', models.PositiveIntegerField(default=0, help_text='Character offset where this note is placed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.OneToOneField(blank=True, help_text='Optional: link to a highlight this note is attached to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='learning.userhighlight')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['topic', 'position_offset'],
            },
        ),
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='User marked this topic as completed.')),
                ('last_read_section', models.CharField(blank=True, help_text='ID/anchor of the last section the user was reading.', max_length=255)),
                ('reading_time_seconds', models.PositiveIntegerField(default=0, help_text='Total cumulative reading time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Progress',
                'verbose_name_plural': 'Topic Progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
