# Generated by Django 6.0.2 on 2026-03-01 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_estimated_pages_specialty_core_display_order_and_more'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicprogress',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0, help_text='Number of tasks completed for this topic (for Learning Plan progress).'),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard'), ('board_basics', 'Board Basics'), ('core', 'CORE'), ('learning_plan', 'Learning Plan')], max_length=15),
        ),
        migrations.CreateModel(
            name='UserStudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('reading', 'Syllabus Reading'), ('quiz', 'Question Bank / Quiz'), ('flashcard', 'Flashcard Review'), ('board_basics', 'Board Basics'), ('core', 'CORE Practice')], max_length=15)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of this study session in seconds.')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='books.book')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='books.specialty')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_anchor', models.CharField(blank=True, help_text='Section/anchor ID within the topic content.', max_length=255)),
                ('label', models.CharField(blank=True, help_text='Auto-generated or user-given label for the bookmark.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'topic', 'section_anchor')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningPlanTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plan_entries', to='books.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plan_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Plan Topic',
                'verbose_name_plural': 'Learning Plan Topics',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
