# Generated by Django 6.0.2 on 2026-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_usertopicprogress_tasks_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='page_number',
            field=models.PositiveIntegerField(default=0, help_text='PDF page number being bookmarked.'),
        ),
        migrations.AddField(
            model_name='userhighlight',
            name='page_number',
            field=models.PositiveIntegerField(default=0, help_text='PDF page number where this highlight is located.'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='page_number',
            field=models.PositiveIntegerField(default=0, help_text='PDF page number where this note is placed.'),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='last_page_read',
            field=models.PositiveIntegerField(default=0, help_text='Last PDF page number the user was reading within the topic range.'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='section_anchor',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Section/anchor ID within the topic content.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userhighlight',
            name='end_offset',
            field=models.PositiveIntegerField(default=0, help_text='Character offset of highlight end within the page.'),
        ),
        migrations.AlterField(
            model_name='userhighlight',
            name='start_offset',
            field=models.PositiveIntegerField(default=0, help_text='Character offset of highlight start within the page.'),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='position_offset',
            field=models.PositiveIntegerField(default=0, help_text='Character offset where this note is placed (within the page).'),
        ),
        migrations.AlterField(
            model_name='usertopicprogress',
            name='last_read_section',
            field=models.CharField(blank=True, help_text='[DEPRECATED] ID/anchor of the last section the user was reading.', max_length=255),
        ),
    ]
