# Generated by Django 6.0.2 on 2026-03-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_userbookmark_page_number_userhighlight_page_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='last_page_read',
        ),
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='last_read_section',
        ),
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='reading_time_seconds',
        ),
        migrations.RemoveField(
            model_name='usertopicprogress',
            name='tasks_completed',
        ),
    ]
